# Generated by Django 4.1.2 on 2023-02-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_category_category_image_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
