# Generated by Django 4.1.2 on 2023-02-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filterprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
