# Generated by Django 4.1.2 on 2023-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_remove_product_user_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=50, unique=True)),
                ('product_image', models.ImageField(unique=True, upload_to='products_image/')),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
