# Generated by Django 4.1.2 on 2023-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_seller_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
