# Generated by Django 4.1.2 on 2023-03-07 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_orderplaced_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cart'),
        ),
    ]
