# Generated by Django 4.1.2 on 2023-03-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_alter_orderplaced_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='size',
        ),
    ]
