# Generated by Django 4.1.2 on 2023-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_category_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory_image',
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='item',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
