# Generated by Django 4.1.2 on 2023-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
