# Generated by Django 4.1.2 on 2023-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_orderplaced_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
