from django.urls import path
from . import views

urlpatterns = [
    path('product_detail/<int:id>/',views.product_detail,name='product_detail'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('filter-products/', views.filter_products, name='filter-products'),
    path('shop/',views.shop,name='shop'),
    path('cart/',views.cart,name='cart'),
    path('wishlist/',views.wishlist,name='wishlist'),
    # path('girls/',views.girls,name='girls'),
    path('size/<int:id>',views.size,name='size'),
    path('color/<int:id>',views.color,name='color'),
    path('price/<int:id>',views.price,name='price'),
    path('checkout/',views.checkout,name='checkout'),
    path('category/',views.category,name='category'),
    # path('category/',views.category,name='category'),
    path('searchbar/',views.searchbar,name='searchbar'),
    path('girls/',views.girls,name='girls'),
    path('boys/',views.boys,name='boys'),
    path('addcart/<int:id>/', views.addcart, name='addcart'),
    path('de_cart/<int:id>/', views.de_cart, name='de_cart'),
    path('plusqty/<int:id>/',views.plusqty,name='plusqty'),
    path('minusqty/<int:id>/',views.minusqty,name='minusqty'),
    path('orders/', views.shop, name='orders'),
    path('checkout_update/',views.checkout_update,name='checkout_update'),
    path('paymentdone/', views.payment_done, name='paymentdone'),
    path('add_wishlist/<int:id>/',views.add_wishlist,name='add_wishlist'),
    path('view_wishlist',views.view_wishlist,name='view_wishlist'),
    path('de_wishlist/<int:id>/',views.de_wishlist,name='de_wishlist'),
    path('showbill/',views.showbill,name='showbill'),
    path('pdf/<int:id>/', views.get,name='pdf'),

    path('complaints/<int:id>/',views.complaints,name='complaints'),
    path('feedback/',views.feedback,name='feedback'),
    

    #seller pages
    path('index/',views.index,name='index'),
    path('forms/',views.forms,name='forms'),
    path('profile/',views.profile,name='profile'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('product/',views.product,name='product'),
    path('table/',views.table,name='table'),
    # path('addproducttable/<int:id>/',views.addproducttable,name='addproducttable'),
    # path('viewproduct',views.view_wishlist,name='view_wishlist'),
    path('productedit/<int:id>/',views.productedit,name='productedit'),
    path('productupdate/',views.productupdate,name='productupdate'),
    path('deleteproduct/<int:id>/',views.deleteproduct,name='deleteproduct'),
    # path('sellerreg/',views.sellerreg,name='sellerreg'),
    # path('sellerlog/',views.sellerlog,name='sellerlog'),
    path('sellreview/',views.sellreview,name='sellreview'),
    path('sellorders/',views.sellorders,name='sellorders'),
    path('initiate/', views.initiate, name='initiate'),
    path('reviewss/<int:id>/',views.reviewss,name='reviewss'),
    path('search_by_voice/', views.search_by_voice, name='search_by_voice'),
    path('market_basket_analysis/',views.market_basket_analysis, name='market_basket_analysis'),
    path('users/',views.users,name='users'),
    path('graph/',views.graph,name='graph'),
    path('viewsellpro/<int:id>/',views.viewsellpro,name='viewsellpro'),
    path('product_detailslog/',views.product_detailslog,name='product_detailslog'),
    path('sellrequest/',views.sellrequest,name='sellrequest'),
    path('sellviewrequest/',views.sellviewrequest,name='sellviewrequest'),
    path('pay/',views.pay,name='pay'),

    path('viewcomplaint/',views.viewcomplaint,name='viewcomplaint'),
    

    #delivery
    path('deliveryorder/',views.deliveryorder,name='deliveryorder'),
    path('deliveryprofile/',views.deliveryprofile,name='deliveryprofile'),
    path('deliveryindex/<int:id>/',views.deliveryindex,name='deliveryindex'),
    path('deliveryproview/<int:id>/',views.deliveryproview,name='deliveryproview'),
    path('verify/',views.verify,name='verify'),
    path('send_order_confirmation_email/', views.send_order_confirmation_email, name='send_order_confirmation_email'),
    path('deliveryconfrim/',views.deliveryconfrim,name='deliveryconfrim'),
   
    #admin
    path('base/',views.adminbase,name='base'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('admin_user/',views.admin_user,name='admin_user'),
    path('admin_seller/',views.admin_seller,name='admin_seller'),
    path('admin_approveupdate/',views.admin_approveupdate,name='admin_approveupdate'),
    path('admin_sellerapprove/<int:id>/',views.admin_sellerapprove,name='admin_sellerapprove'),
    path('admin_delivery/',views.admin_delivery,name='admin_delivery'),
    path('deliverydel/<int:id>/',views.deliverydel,name='deliverydel'),
    path('admin_adddelivery/',views.admin_adddelivery,name='admin_adddelivery'),
    path('admin_addcategory/',views.admin_addcategory,name='admin_addcategory'),
    path('admin_categoryedit/<int:id>/',views.admin_categoryedit,name='admin_categoryedit'),
    path('admin_categoryupdate/',views.admin_categoryupdate,name='admin_categoryupdate'),
    path('admin_categorydelete/<int:id>/',views.admin_categorydelete,name='admin_categorydelete'),
    path('admin_viewcategory/',views.admin_viewcategory,name='admin_viewcategory'),
    path('admin_subaddcategory/',views.admin_subaddcategory,name='admin_subaddcategory'),
    path('admin_deletesub/<int:id>/',views.admin_deletesub,name='admin_deletesub'),
    path('admin_editsub/<int:id>/',views.admin_editsub,name='admin_editsub'),
    path('admin_updatesub/',views.admin_updatesub,name='admin_updatesub'),
    path('admin_subviewcategory/',views.admin_subviewcategory,name='admin_subviewcategory'),
    path('admin_addproduct/',views.admin_addproduct,name='admin_addproduct'),
    path('admin_viewproduct/',views.admin_viewproduct,name='admin_viewproduct'),
    path('admin_addsize/',views.admin_addsize,name='admin_addsize'),
    path('admin_editsize/<int:id>/',views.admin_editsize,name='admin_editsize'),
    path('admin_updatesize/',views.admin_updatesize,name='admin_updatesize'),
    path('admin_viewsize/',views.admin_viewsize,name='admin_viewsize'),
    path('deletesize/<int:id>/',views.deletesize,name='deletesize'),
    path('admin_vieworder/',views.admin_vieworder,name='admin_vieworder'),
    path('order_detailslog/',views.order_detailslog,name='order_detailslog'),
    path('seller_detailslog/',views.seller_detailslog,name='seller_detailslog'),


    path('admin_deleteproduct/',views.admin_deleteproduct,name='admin_deleteproduct'),
    path('admin_viewproduct/<int:id>/',views.admin_viewproduct,name='admin_viewproduct'),
    path('admin_viewallproduct/',views.admin_viewallproduct,name='admin_viewallproduct'),
    path('admin_sellerpayment/',views.admin_sellerpayment,name='admin_sellerpayment'),

    path('admin_viewrequest/',views.admin_viewrequest,name='admin_viewrequest'),

    

]
