# Generated by Django 4.1.2 on 2023-02-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0004_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
