# Generated by Django 4.1.2 on 2023-02-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0005_seller_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_user',
        ),
    ]
