# Generated by Django 4.1.2 on 2023-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0006_remove_seller_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
