# Generated by Django 4.1.2 on 2023-02-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0007_seller_is_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject')], default='None', max_length=50),
        ),
    ]
