# Generated by Django 4.1.2 on 2023-02-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0008_delete_seller_account_role_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('contact', models.BigIntegerField(default=0)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('pincode', models.BigIntegerField(default=0)),
                ('password', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
    ]
