# Generated by Django 4.1.2 on 2023-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0009_seller_remove_account_role_remove_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
