# Generated by Django 4.1.2 on 2023-02-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0010_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('customer', 'customer'), ('seller', 'seller'), ('None', 'None')], default='', max_length=100),
        ),
    ]
