# Generated by Django 4.1.2 on 2023-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0011_account_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staffappproved',
            field=models.BooleanField(default=False),
        ),
    ]
