# Generated by Django 4.1.2 on 2023-02-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0012_account_is_staffappproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_staffappproved',
            new_name='approved_staff',
        ),
    ]
