# Generated by Django 4.1.2 on 2023-03-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0013_rename_is_staffappproved_account_approved_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
