# Generated by Django 4.1.2 on 2023-04-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0014_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
